config/routes.rb
# http://localhost:3000/about # ADD COMMENT LATER
Rails.application.routes.draw do

  # The route is made of:
  # 1) HTTP Verb (GET/POST/PATCH/PUT/DELETE)
  # 2) Relative Url Path (/, or /adilson, or /bands)
  # 3) Which controller responds to this request
  # 4) What action of this controller is going to be executed

  # SYNTAX
  # verb '/path', to: 'controller_name#action', as: :prefix_name

  # get '/', to: 'pages#home'
  root to: 'pages#home'


  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

# 1st Thing to Do: Think About the Route!!!
# 2nd Thing to Do: Go to the Controller and Code What You Need
# 3rd Thing: Implement the View!

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # What is an action?
  # A method defined within a Controller

  # Instance Variable
  # Allows you to share a variable in a controller action
  # with the view of the same name!

  # IMPORTANT!!
  # The instance variable defined within an action
  # IS NOT SHARED with the other actions

  def about
  end

  def contact
  end

  def home
    # ACCESS INFORMATION FROM THE FORM
    # USING THE PARAMS!
    params # LIKE A HASH
    params #=> { house: 'Gryffindor'}
    params[:house] #=> 'Gryffindor'
    @school = 'Hogwarts'
    @houses = ['Gryffindor', "Slytherin", 'Ravenclaw', 'Hufflepuff']

    if params[:house].present?
      @houses = @houses.select do |house_name|
        house_name == params[:house]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro1408</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# here will appear on every page %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>First Rails Page 🚀</h1>

<%= link_to 'Back to home', root_path %>

app/views/pages/contact.html.erb
<h1>Contact us</h1>

<%= link_to 'Back to home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to Rails #1408</h1>


<p>Time now is: <%= Time.now %></p>
<% Time.now %>


<p><%= @school %></p>



<%# ABOUT FORMS %>
<%# Name of the parameters that arrive in the controller
    comes from the name of a form's inputs %>
<%# The form can make the request for another route
    because it will work the same way :ok %>

<form action="/" method="get">
  <input type="text" name="house" id="house" value="<%= params[:house] %>">
  <input type="submit" value="Filter">
</form>

<p>This is the <strong>params</strong>: <%= params %></p>

<ul>
  <% @houses.each do |house| %>
    <li><%= house %></li>
  <% end %>
</ul>

<%# LINK %>

<%# WE DONT USE A TAG %>
<a href="/contact">Contacts</a>
                          <%# prefix_path %>
<%= link_to 'Talk to us', contact_path %>
<%= link_to 'Know us', about_path %>